### ISSUE TITLE
Not all user attributes are available in `userInfo` in JSPs

### ISSUE THREAD

**Issue by bjagg** [Jasig/uPortal#1326] opened 2018-09-11 18:56 UTC
**Describe the bug**
Additional user attributes are not available in in JSPs via `userInfo`.

**To Reproduce**
1. Configure an external user attribute source
2. For testing, modify greetings.jsp and add `${userInfo}` near name
3. Log in with user that has extra attributes
4. See that attributes are missing in output but are present in uPortal
  - confirm through logs or as admin using User Portlet tool

**Expected behavior**
Additional attributes should be present in `${userInfo}`

**Additional context**
Default user attributes, `displayName, user.login.id, impersonating` are usually present
There may be some hidden configuration that filters attributes in `userInfo`, but it is not apparent from documentation, reviewing context files, or searching source.
Consider adding the following to logback.xml for debugging:
```xml
 <logger name="org.apereo.services.persondir.support" additivity="false" level="TRACE">
    <appender-ref ref="PORTAL"/>
  </logger>
```

**Comment by jgribonvald** [comment] 2018-09-11 19:08
To avoid this problem i use the personManager bean into jspInvoker

**Comment by drewwills** [comment] 2018-09-11 20:48
This is a great writeup -- all of them should be this good.

    There may be some hidden configuration that filters attributes in `userInfo`

Are the missing attributes listed here?...
  - https://github.com/Jasig/uPortal/blob/master/uPortal-webapp/src/main/webapp/WEB-INF/portlet.xml#L1160

**Comment by bjagg** [comment] 2018-09-11 21:27
Yeah, in my rush, I forgot about the portlet configuration. I will add documentation around this.

Thanks!

**Comment by drewwills** [comment] 2018-09-11 21:37
IMHO this episode makes a nice anecdotal example of how portlets are frustrating.

**Comment by bjagg** [comment] 2018-09-11 21:38
Yep, I agree

**Comment by drewwills** [comment] 2018-12-12 23:31
Folks -- I'm going to close this ticket because the thing it describes is actually "working as intended."

If Benito (or anyone) adds documentation that helps in this area, that would be welcome.

**Closed by drewwills** 2018-12-12 23:31 UTC
Labels: enhancement, work in progress
